### ISSUE TITLE
Crear Modelo Conceptual

### ISSUE THREAD

**Issue by seguraedwin5** [tonyzl/TransporteBusesApp#2]

**Comment by pmap1986** [comment]
Con esto te refieres al diagrama de clases o Mockups?

**Comment by seguraedwin5** [comment]
Si, esto se refiere a los diferentes diagramas que relacionan la lógica de la aplicación, porque aún no lo tenemos, te gustaría hacer esta tarea?

**Comment by seguraedwin5** [comment]
se Crea el modelo de clases y base de datos
![image](https://user-images.githubusercontent.com/51142779/189436116-fbb8b44e-9cdc-499d-be3b-ddaca99a7ab1.png)
![image](https://user-images.githubusercontent.com/51142779/189436190-189dfcb1-3524-4dae-b2a1-7899557bc439.png)
